---
catalog: ""
git:
  url: https://github.com/tanzu-end-to-end/tap-gitops-reference
  ref: origin/h2o
paths:
  - clusters/common/config
  - clusters/appref-2/config
tap:
  registry:
    host: harbor.h2o-4-1396.h2o.vmware.com
    location: tap/tbs
  supplychainregistry:
    host: harbor.h2o-4-1396.h2o.vmware.com
    location: tap/sc
  base:
    domain: run.h2o-4-1396.h2o.vmware.com
