#@data/values

#@overlay/match-child-defaults missing_ok=True
---
externaldns:
  version: "0.10.0+vmware.1-tkg.1"
  namespace: tap-install
contour:
  version: "1.20.2+vmware.1-tkg.1"
  namespace: tap-install
certmanager:
  version: "1.7.2+vmware.1-tkg.1"
  namespace: tap-install
tds:
  version: "1.0.2"
  namespace: tap-install
