
#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ def othersecret():
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: route53-credentials
  namespace: tanzu-system-service-discovery
spec:
  fromNamespace: tap-install
#@ end
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: externaldns
  namespace: #@ data.values.externaldns.namespace
  annotations:
    kapp.k14s.io/change-group: externaldns
    kapp.k14s.io/change-rule: "delete after deleting tap"
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.1: external-dns-security-overlay

spec:
  packageRef:
    refName: external-dns.tanzu.vmware.com
    versionSelection:
      prereleases: {}
      constraints: #@ str(data.values.externaldns.version)
  serviceAccountName: tap-install-gitops-sa
  values:
  - secretRef:
      name: externaldns-values
---
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-security-overlay
stringData:
  othersecret.yaml: #@ yaml.encode(othersecret())
  